### PR TITLE
Set env var and tag plugin identify for metrics

### PR DESCRIPTION
**Pull request by chanseokoh**
In relation to #4.

I'd like to set this now so that we don't forget it before the next release. How about "app-maven-plugin"?

Note: we still need to set ENVIRONMENT_VERSION.

### CODE REVIEW

**Comment by meltsufin** [comment]
Why not set the ENVIRONMENT_VERSION as part of this PR?

**Comment by chanseokoh** [comment]
I can do that, but I'm not familiar with Maven. I see it's currently 0.1.0-SNAPSHOT in pom.xml. How can I retrieve it?

**Comment by meltsufin** [comment]
I found a way to get this info. See my commit. I had to move this out of the constructor though because of the component injection.

**Comment by chanseokoh** [comment]
Great! Shall we merge this?

**Comment by meltsufin** [comment]
Sure :ship:

**Comment by chanseokoh** [comment]
Just to confirm: `pluginDescriptor.getArtifactId()` will return "app-maven-plugin", won't it?

**Comment by meltsufin** [comment]
Yes, it should.

**Comment by chanseokoh** [comment]
Sorry. On second thought, isn't it "gcp-app-maven-plugin" if you look at pom.xml?

**Comment by meltsufin** [comment]
Sorry, yes, missed that prefix too. :)

**Pull request merged**
