### PR TITLE
Remove application and version from appengine-web.xml test app

### LINKED ISSUE #67: test cases include the application id and version in the appengine-web.xml
storing the ID and version in the appengine-web.xml is no longer the recommended way to do it, and technically shouldn't work against the gcloud tooling.

### PR DESCRIPTION
**Pull request by meltsufin**
Fixes #67.

### CODE REVIEW

**Comment by meltsufin** [comment]
Fails for now with `Bad configuration: No app id supplied and XML files have no <application> element`.
Waiting for the fix in AppCfg staging to make it into the Cloud SDK.

**Comment by patflynn** [comment]
It sounds like we need to make the project ID flag required on the plugin
for now instead.  It's problematic that the staging code requires it to be
set in the xml if it's not passed as a flag, but strips it from the
generated app.yaml regardless.

**Comment by loosebazooka** [comment]
What do we want to do about this PR here?

**Comment by meltsufin** [comment]
@loosebazooka This is ready to be merged in now. It just needs your approval.

**Pull request merged**
