### PR TITLE
specify appengine config directory rather than app.yaml path

### PR DESCRIPTION
**Pull request by meltsufin**
This is a sync up with the common tools library change.
@loosebazooka

### CODE REVIEW

**Comment by loosebazooka** [comment]
:ship:

**Comment by patflynn** [comment]
This is a bit different from the way that gcloud models it.  They derive the directory context from the location of the app.yaml parameter.

**Comment by meltsufin** [comment]
We can do it either way. It's even conceivable to overload the parameter to accept either app.yaml or directory path. @loosebazooka @arouzrokh

**Comment by loosebazooka** [comment]
I think the problem is that gcloud doesn't try to deploy all the yaml files along with it. In gradle, I'm accepting both, the library code switches based on whether it's a single directory or a list of files. Even considering all that, the solution I put in might need to be worked on.

**Pull request merged**
