### PR TITLE
Primary and secondary Dockerfile location defaults

### LINKED ISSUE #22: Look at both src/main/docker/Dockerfile and src/main/appengine/Dockerfile
src/main/docker has priority
src/main/appengine is for legacy support

### PR DESCRIPTION
**Pull request by meltsufin**
Fixes #22.

@loosebazooka @patflynn

### CODE REVIEW

**Comment by meltsufin** [comment]
@loosebazooka I pulled in the unit tests branch into this. Please review that PR first so that the diffs are simpler here.

**Comment by meltsufin** [comment]
Ready for review.

**Comment by loosebazooka** [comment]
I think this looks fine, but I'm working on a change to make docker a directory based on the team's discussions on this. So :ship: for now, but it's probably going to change.

**Comment by meltsufin** [comment]
Sounds good, thanks!

**Pull request merged**
