### PR TITLE
Allow licenses use 2017 as well as 2016 for copyright year

### PR DESCRIPTION
**Pull request by akerekes**

### CODE REVIEW

**Comment by chanseokoh** [comment]
I'm just wondering if `.` (dot) should also be escaped.

**Comment by akerekes** [comment]
@chanseokoh yeah, it should be.

**Comment by patflynn** [comment]
Shouldn't this just be 2017?

**Comment by meltsufin** [comment]
For new code, probably, but I'm not sure about existing files. Do you just go every Jan 1st, and change all headers everywhere?

**Comment by akerekes** [comment]
http://stackoverflow.com/questions/2390230/do-copyright-dates-need-to-be-updated

>The copyright notice on a work establishes a claim to copyright. The date on the notice establishes how far back the claim is made.

**Comment by patflynn** [comment]
No we don't change all the headers. We just update our copyright template
to 2017.
https://github.com/GoogleCloudPlatform/google-cloud-intellij/blob/master/.idea/copyright/Google_Copyright.xml

IntelliJ has the habit of updating the copyright though on files that you
change in a commit.

**Pull request merged**
