### PR TITLE
Rename artifactId from gcp-app-maven-plugin to app-maven-plugin

### LINKED ISSUE #26: Rename artifactId from gcp-app-maven-plugin to app-maven-plugin
Currently, the plugin artifactId is inconsistent with the GitHub project name, and the gradle plugin artifactId (app-gradle-plugin). When artifactId name is changed to `app-maven-plugin`, we will have to make sure to customize the goal prefix to be `gcp-app` instead of the default `app`.

### PR DESCRIPTION
**Pull request by meltsufin**
Fixes #26.

### CODE REVIEW

**Comment by meltsufin** [comment]
@chanseokoh this affects metrics

**Comment by chanseokoh** [comment]
@meltsufin Acknowledged!

**Comment by loosebazooka** [comment]
and our samples.

**Comment by meltsufin** [comment]
Good to go? We'll update the docs and samples immediately after.

**Comment by loosebazooka** [comment]
:ship:

**Pull request merged**
