### PR TITLE
Correctly updates gcloud in continuous_mac.sh

### LINKED ISSUE #222: continuous_mac.sh uses old version of gcloud
`continuous_mac.sh` downloads the latest Cloud SDK but does not actually set the path of gcloud. This can be seen by failures on kokoro-macos such as:

```
testRunAsyncV2Alpha: [ERROR] Failed to execute goal com.google.cloud.tools:appengine-maven-plugin:1.3.2-SNAPSHOT:start (default-cli) on project standard-project: Execution default-cli of goal com.google.cloud.tools:appengine-maven-plugin:1.3.2-SNAPSHOT:start failed: Requires version 171.0.0 or later but found version 159.0.0 -> [Help 1]
```

### PR DESCRIPTION
**Pull request by coollog**
Fixes #222

### CODE REVIEW

**Comment by loosebazooka** [comment]
can you explain?

**Comment by coollog** [comment]
Oh this is a test PR, not for review haha. I'm trying to fix the breaking macos build in https://github.com/GoogleCloudPlatform/app-maven-plugin/pull/219

**Comment by coollog** [comment]
Okay, now this is a real PR, as this is what we want to do. The continuous_mac.sh script downloaded the Cloud SDK but did not actually have it be used. This fixes that by having the correct symlink to the downloaded gcloud.

**Comment by loosebazooka** [comment]
should we just use the cloudSDK on the mac already, similar to the linux build?

**Comment by coollog** [comment]
The Cloud SDK on the mac is outdated: #222

**Comment by chanseokoh** [comment]
If so, perhaps we could just do `gcloud update components` with the built-in Cloud SDK.

**Comment by coollog** [comment]
Okay just doing that worked! Thanks!

**Pull request merged**
