### PR TITLE
do not delete staging directory by default

### PR DESCRIPTION
**Pull request by loosebazooka**
This allows users to inject arbitrary files into staging using maven `copy-resources` `copy-dependencies` goals

### CODE REVIEW

**Comment by chanseokoh** [comment]
So, are we going to document somewhere something like "the default staging directory is target/appengine-staging where gcloud will be invoked to deploy, and if needed, you can copy extra files (for example) using `copy-resources`"?

**Comment by loosebazooka** [comment]
Yeah, basically anyone who is using those goals will have to configure those correctly to reference the appengine staging directory (either the default or whatever they have configured)

**Comment by loosebazooka** [comment]
I should also add that we will still allow the use to add in files using `extraFilesDirectories`

**Comment by loosebazooka** [comment]
@ludoch how do you feel about this solution?

**Pull request merged**
