### PR TITLE
Fix for old workaround:

### LINKED ISSUE #135: Remove old workaround
See https://github.com/GoogleCloudPlatform/app-maven-plugin/search?utf8=%E2%9C%93&q=workAroundNonJava7Version

The method workAroundNonJava7Version() should now be removed, as it is not needed anymore with the new local SDK.

### PR DESCRIPTION
**Pull request by ludoch**
Fixes #135

### CODE REVIEW

**Comment by ludoch** [comment]
When/how do we run continuous-integration/appveyor/branch  tests?

**Comment by meltsufin** [comment]
End to end remote tests should be run post commit on master, and daily.

**Comment by ludoch** [comment]
Daily? I'ts been 24+ hours:-)

**Comment by meltsufin** [comment]
Weekdays only, I believe! :)
No, but in this PR there is some other issue where AppVeyor GitHub hook got stuck.
I'll try to straighten it out.

**Pull request merged**
